### ISSUE TITLE
index.html pointing to app.js

### ISSUE THREAD

**Issue by pvoliveira** [johanbrandhorst/grpcweb-boilerplate#1]
Hi! 
I'm on windows and I don't know if is the problem, but the html loaded when run isn't the same that in *./frontend/html/index.html*. I replaced "frontend.js" to "app.js" in the project then works.

**Comment by johanbrandhorst** [comment]
Ah, I may need to regenerate it, I'll take a quick look.

**Comment by johanbrandhorst** [comment]
Fixed in https://github.com/johanbrandhorst/grpcweb-boilerplate/commit/529fdf884d8e8d67bd841d51e06804826db84497, thanks for raising!
